[tool.black]
line-length = 79
skip-string-normalization = true

[tool.isort]
profile = 'black'
skip = [
    '.gitignore',
    '.dockerignore',
    'env',
    'venv',
    'start.sh'
    ]
extend_skip = [
    '.md',
    '.json',
    ]
known_local_folder = [
    'users',
    ]

[tool.flake8]
ignore = [
    'BLK100',
    'W503',
    'E501',
    'R504'
    ]
exclude = [
    '*/tests/',
    'tests/',
    'venv/',
    'env/',
    ]
per-file-ignores = [
    '*/settings.py:E501',
    ]
max-complexity = 11
